# Numpy 

* NumPy operations perform complex computations on entire arrays without the need for Python for loops.
* Fast vectorized array operations for data munging and cleaning, subsetting and filtering, transformation, and any other kinds of computations
* Common array algorithms like sorting, unique, and set operations
* Efficient descriptive statistics and aggregating/summarizing data
* Data alignment and relational data manipulations for merging and joining together heterogeneous datasets
* Expressing conditional logic as array expressions instead of loops with if-elif-else branches
* Group-wise data manipulations (aggregation, transformation, function application)

In [1]:
import numpy as np

# Faster Computation

In [2]:
np_array = np.arange(1000000)
lst_num = list(range(1000000))

In [3]:
%%time 
for i in range(10): np_array = np_array*2

CPU times: user 6.13 ms, sys: 19.1 ms, total: 25.3 ms
Wall time: 23.2 ms


In [4]:
%%time
for i in range(10): lst_num = [i*2 for i in lst_num]

CPU times: user 405 ms, sys: 66.6 ms, total: 472 ms
Wall time: 472 ms


## Inspection of Structure

In [5]:
lst_num = [1,20,15,4,5]
for num in lst_num:
    print(id(num))

94261447332608
94261447333216
94261447333056
94261447332704
94261447332736


<html>
    <table><caption> Lists</caption>
        <tr><th>Elements</th><th>Reference</th></tr>
        <tr><th>1</th><th>94367780467456</th></tr>
        <tr><th>20</th><th>94367780468064</th></tr>
        <tr><th>15</th><th>94367780467904</th></tr>
        <tr><th>4</th><th>94367780467552</th></tr>
        <tr><th>5</th><th>94367780467584</th></tr>        
    </table>
 </html>

In [6]:
arr_test = np.random.randint(1,30,size = (5,1)).ravel()
for ele in arr_test:
    print(f'{ele}',id(ele))

8 139682550040176
27 139682550039984
24 139682550040176
20 139682550039984
26 139682550040176


# ndarray

In [7]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [8]:
for element in arr1:
    print(element)

1
2
3
4
5


In [32]:
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [12]:
arr1.ndim,arr2.ndim

(1, 2)

In [13]:
arr2.shape

(2, 5)

In [14]:
arr2.size

10

<dl class="docutils">
<dt>ndarray.ndim</dt>
<dd>the number of axes (dimensions) of the array.</dd>
<dt>ndarray.shape</dt>
<dd>the dimensions of the array. This is a tuple of integers indicating
the size of the array in each dimension. For a matrix with <em>n</em> rows
and <em>m</em> columns, <code class="docutils literal notranslate"><span class="pre">shape</span></code> will be <code class="docutils literal notranslate"><span class="pre">(n,m)</span></code>. The length of the
<code class="docutils literal notranslate"><span class="pre">shape</span></code> tuple is therefore the number of axes, <code class="docutils literal notranslate"><span class="pre">ndim</span></code>.</dd>
<dt>ndarray.size</dt>
<dd>the total number of elements of the array. This is equal to the
product of the elements of <code class="docutils literal notranslate"><span class="pre">shape</span></code>.</dd>
<dt>ndarray.dtype</dt>
<dd>an object describing the type of the elements in the array. One can
create or specify dtype’s using standard Python types. Additionally
NumPy provides types of its own. numpy.int32, numpy.int16, and
numpy.float64 are some examples.</dd>
<dt>ndarray.itemsize</dt>
<dd>the size in bytes of each element of the array. For example, an
array of elements of type <code class="docutils literal notranslate"><span class="pre">float64</span></code> has <code class="docutils literal notranslate"><span class="pre">itemsize</span></code> 8 (=64/8),
while one of type <code class="docutils literal notranslate"><span class="pre">complex32</span></code> has <code class="docutils literal notranslate"><span class="pre">itemsize</span></code> 4 (=32/8). It is
equivalent to <code class="docutils literal notranslate"><span class="pre">ndarray.dtype.itemsize</span></code>.</dd>
<dt>ndarray.data</dt>
<dd>the buffer containing the actual elements of the array. Normally, we
won’t need to use this attribute because we will access the elements
in an array using indexing facilities.</dd>
</dl>

In [16]:
type(arr2),arr2.dtype

(numpy.ndarray, dtype('int64'))

In [21]:
arr2 = np.array([1,2,3,5,'34'],dtype = np.float64)

In [23]:
arr2,arr2.dtype

(array([ 1.,  2.,  3.,  5., 34.]), dtype('float64'))

In [26]:
arr1 = np.array([1,2,3,4],dtype ='i2')

In [28]:
arr1.dtype

dtype('int16')

In [27]:
arr1.itemsize

2

<html>
    <table id="table_array_dtypes"><caption><span class="label">Table 4-2. </span><b>NumPy data types</b></caption><thead><tr><th>Type</th><th>Type code</th><th>Description</th></tr></thead><tbody><tr><td><code>int8, uint8</code></td><td><code>i1, u1</code></td><td>Signed <a data-type="indexterm" data-primary="int8 data type" id="idm140621970284992"></a><a data-type="indexterm" data-primary="uint8 data type" id="idm140621970284128"></a>and unsigned 8-bit (1 byte) integer types</td></tr><tr><td><code>int16, uint16</code></td><td><code>i2, u2</code></td><td>Signed <a data-type="indexterm" data-primary="int16 data type" id="idm140621970281952"></a><a data-type="indexterm" data-primary="uint16 data type" id="idm140621970281088"></a>and unsigned 16-bit integer types</td></tr><tr><td><code>int32, uint32</code></td><td><code>i4, u4</code></td><td>Signed <a data-type="indexterm" data-primary="int32 data type" id="idm140621970278912"></a><a data-type="indexterm" data-primary="uint32 data type" id="idm140621970278048"></a>and unsigned 32-bit integer types</td></tr><tr><td><code>int64, uint64</code></td><td><code>i8, u8</code></td><td>Signed <a data-type="indexterm" data-primary="int64 data type" id="idm140621970275872"></a><a data-type="indexterm" data-primary="uint64 data type" id="idm140621970275008"></a>and unsigned 64-bit integer types</td></tr><tr><td><code>float16</code></td><td><code>f2</code></td><td>Half-precision<a data-type="indexterm" data-primary="float16 data type" id="idm140621970272832"></a> floating point</td></tr><tr><td><code>float32</code></td><td><code>f4 or f</code></td><td>Standard <a data-type="indexterm" data-primary="float32 data type" id="idm140621970270592"></a>single-precision floating point; compatible with C
              float</td></tr><tr><td><code>float64</code></td><td><code>f8 or d</code></td><td>Standard <a data-type="indexterm" data-primary="float64 data type" id="idm140621970268384"></a>double-precision floating point; compatible with C
              double and Python <code>float</code>
              object</td></tr><tr><td><code>float128</code></td><td><code>f16 or g</code></td><td>Extended-precision <a data-type="indexterm" data-primary="float128 data type" id="idm140621970265728"></a>floating point</td></tr><tr><td><code>complex64</code>, <span class="keep-together"><code>complex128</code></span>, <span class="keep-together"><code>complex256</code></span></td><td><code>c8, c16, c32</code></td><td>Complex <a data-type="indexterm" data-primary="complex64 data type" id="idm140621970261792"></a><a data-type="indexterm" data-primary="complex128 data type" id="idm140621970260928"></a><a data-type="indexterm" data-primary="complex256 data type" id="idm140621970260096"></a>numbers represented by two 32, 64, or 128 floats,
              respectively</td></tr><tr><td><code>bool</code></td><td>?</td><td>Boolean <a data-type="indexterm" data-primary="bool data type" id="idm140621970258048"></a>type storing <code>True</code> and <code>False</code> values</td></tr><tr><td><code>object</code></td><td>O</td><td>Python <a data-type="indexterm" data-primary="object data type" id="idm140621970255040"></a>object type; a value can be any Python
              object</td></tr><tr><td><code>string_</code></td><td>S</td><td>Fixed-length <a data-type="indexterm" data-primary="string_ data type" id="idm140621970252960"></a>ASCII string type (1 byte per character); for
              example, to create a string dtype with length 10, use <code>'S10'</code></td></tr><tr><td><code>unicode_</code></td><td>U</td><td>Fixed-length <a data-type="indexterm" data-primary="unicode_ data type" id="idm140621970250464"></a>Unicode type (number of bytes platform specific);
              same specification semantics as <code>string_</code> (e.g., <code>'U10'</code>)</td></tr></tbody></table>
    </html>
    

## Data type while creation

In [29]:
arr3 = np.array([1,2,3,4], dtype = float)
arr3.dtype

dtype('float64')

## Array creation with function

In [30]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
arr2.shape

(2, 5)

In [34]:
np.zeros_like(arr2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [43]:
arr1_mod = np.ones((4,2),dtype = np.int32)
arr1_mod.dtype

dtype('int32')

In [44]:
np.ones((4,2),dtype = int),np.ones_like(arr2)

(array([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [46]:
list(range(5,50,3))

[5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47]

In [45]:
np.arange(5,50,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [50]:
np.linspace(0,20,100)

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

<html>
    <table id="table_array_ctor"><caption><span class="label">Table 4-1. </span>Array creation functions</caption><thead><tr><th>Function</th><th>Description</th></tr></thead><tbody><tr><td><code>array</code></td><td>Convert input <a data-type="indexterm" data-primary="array function" id="idm140621970503616"></a>data (list, tuple, array, or other sequence type)
              to an ndarray either by inferring a dtype or explicitly
              specifying a dtype; copies the input data by default</td></tr><tr><td><code>asarray</code></td><td>Convert input to <a data-type="indexterm" data-primary="asarray function" id="idm140621970501616"></a>ndarray, but do not copy if the input is already
              an ndarray</td></tr><tr><td><code>arange</code></td><td>Like the <a data-type="indexterm" data-primary="arange function" id="idm140621970499824"></a><a data-type="indexterm" data-primary="range function" id="idm140621970498960"></a>built-in <code>range</code>
              but returns an ndarray instead of a list</td></tr><tr><td><code>ones, ones_like</code></td><td>Produce an array <a data-type="indexterm" data-primary="" data-startref="oneskb" id="idm140621970496752"></a><a data-type="indexterm" data-primary="ones_like function" id="idm140621970495616"></a>of all 1s with the given shape and dtype;
              <code>ones_like</code> takes another array
              and produces a ones array of the same shape and dtype</td></tr><tr><td><code>zeros, zeros_like</code></td><td>Like <code>ones</code> and <code>ones_like</code> but <a data-type="indexterm" data-primary="" data-startref="zeroskb" id="idm140621970492432"></a><a data-type="indexterm" data-primary="zeros_like function" id="idm140621970491296"></a>producing arrays of 0s instead</td></tr><tr><td><code>empty, empty_like</code></td><td>Create new arrays by <a data-type="indexterm" data-primary="" data-startref="emptykb" id="idm140621970489536"></a><a data-type="indexterm" data-primary="empty_like function" id="idm140621970488400"></a>allocating new memory, but do not populate with
              any values like <code>ones</code> and
              <code>zeros</code></td></tr><tr><td><code>full, full_like</code></td><td>Produce an array <a data-type="indexterm" data-primary="full function" id="idm140621970485808"></a><a data-type="indexterm" data-primary="full_like function" id="idm140621970484944"></a>of the given shape and dtype with all values set
              to the indicated “fill value” <code>full_like</code> takes another array and
              produces a filled array of the same shape and dtype</td></tr><tr><td><code>eye, identity</code></td><td>Create a <a data-type="indexterm" data-primary="eye function" id="idm140621970482544"></a><a data-type="indexterm" data-primary="identity function" id="idm140621970481680"></a>square N × N identity matrix (1s on the diagonal
              <a data-type="indexterm" data-primary="" data-startref="nd4.1.1" id="idm140621970480720"></a>and 0s elsewhere)</td></tr></tbody></table>
</html>

### Array creating with random numbers

In [51]:
np.random?

In [69]:
np.random.seed(10)

print(np.random.randint(1,10,size = (3,2)))

print(np.random.randint(1,10,size = (3,2)))

[[5 1]
 [2 1]
 [2 9]]
[[1 9]
 [7 5]
 [4 1]]


In [76]:
np.arange(5,65,5).reshape(3,4)

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

# Basic Operations

In [77]:
a = np.arange(2,10,2)
b = np.arange(1,9,2)
a,b

(array([2, 4, 6, 8]), array([1, 3, 5, 7]))

In [78]:
a+b

array([ 3,  7, 11, 15])

In [79]:
a*b

array([ 2, 12, 30, 56])

In [80]:
arow1 = np.arange(1,5,2)
arow2 = np.arange(2,6,2)
A = np.array((arow1,arow2))
A

array([[1, 3],
       [2, 4]])

In [81]:
brow1 = np.arange(0,3,2)
brow2 = np.arange(1,4,2)
B = np.array((brow1,brow2))
B

array([[0, 2],
       [1, 3]])

In [82]:
A*B

array([[ 0,  6],
       [ 2, 12]])

In [83]:
A .dot(B)

array([[ 3, 11],
       [ 4, 16]])

In [84]:
A @ B

array([[ 3, 11],
       [ 4, 16]])

## Vector Operations 


In [85]:
X = np.arange(5,65,5).reshape(4,3)
X

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

* axis = 0 columnwise vectors
* axis = 1 rowwise vectors

In [88]:
X.min(axis = 1),X.min(axis = 0),X.min()

(array([ 5, 20, 35, 50]), array([ 5, 10, 15]), 5)

In [93]:
X.argmin(axis = 1),X.argmin(axis = 1),X.argmin()

(array([0, 0, 0, 0]), array([0, 0, 0, 0]), 0)

In [94]:
X.max(axis = 1),X.max(axis = 0),X.max()

(array([15, 30, 45, 60]), array([50, 55, 60]), 60)

In [95]:
X.argmax(axis = 1),X.argmax(axis = 0),X.argmax()

(array([2, 2, 2, 2]), array([3, 3, 3]), 11)

In [89]:
X.sum(axis = 1)

array([ 30,  75, 120, 165])

In [92]:
X.cumsum(axis = 0),X.cumsum(axis = 1),X.cumsum()

(array([[  5,  10,  15],
        [ 25,  35,  45],
        [ 60,  75,  90],
        [110, 130, 150]]),
 array([[  5,  15,  30],
        [ 20,  45,  75],
        [ 35,  75, 120],
        [ 50, 105, 165]]),
 array([  5,  15,  30,  50,  75, 105, 140, 180, 225, 275, 330, 390]))

<div class="section" id="functions-and-methods-overview">
<h3>Functions and Methods Overview<a class="headerlink" href="#functions-and-methods-overview" title="Permalink to this headline">¶</a></h3>
<p>Here is a list of some useful NumPy functions and methods names
ordered in categories. See <a class="reference internal" href="../reference/routines.html#routines"><span class="std std-ref">Routines</span></a> for the full list.</p>
<dl class="docutils">
<dt>Array Creation</dt>
<dd><a class="reference internal" href="../reference/generated/numpy.arange.html#numpy.arange" title="numpy.arange"><code class="xref py py-obj docutils literal notranslate"><span class="pre">arange</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.array.html#numpy.array" title="numpy.array"><code class="xref py py-obj docutils literal notranslate"><span class="pre">array</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.copy.html#numpy.copy" title="numpy.copy"><code class="xref py py-obj docutils literal notranslate"><span class="pre">copy</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.empty.html#numpy.empty" title="numpy.empty"><code class="xref py py-obj docutils literal notranslate"><span class="pre">empty</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.empty_like.html#numpy.empty_like" title="numpy.empty_like"><code class="xref py py-obj docutils literal notranslate"><span class="pre">empty_like</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.eye.html#numpy.eye" title="numpy.eye"><code class="xref py py-obj docutils literal notranslate"><span class="pre">eye</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.fromfile.html#numpy.fromfile" title="numpy.fromfile"><code class="xref py py-obj docutils literal notranslate"><span class="pre">fromfile</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.fromfunction.html#numpy.fromfunction" title="numpy.fromfunction"><code class="xref py py-obj docutils literal notranslate"><span class="pre">fromfunction</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.identity.html#numpy.identity" title="numpy.identity"><code class="xref py py-obj docutils literal notranslate"><span class="pre">identity</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.linspace.html#numpy.linspace" title="numpy.linspace"><code class="xref py py-obj docutils literal notranslate"><span class="pre">linspace</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.logspace.html#numpy.logspace" title="numpy.logspace"><code class="xref py py-obj docutils literal notranslate"><span class="pre">logspace</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.mgrid.html#numpy.mgrid" title="numpy.mgrid"><code class="xref py py-obj docutils literal notranslate"><span class="pre">mgrid</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.ogrid.html#numpy.ogrid" title="numpy.ogrid"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ogrid</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.ones.html#numpy.ones" title="numpy.ones"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ones</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.ones_like.html#numpy.ones_like" title="numpy.ones_like"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ones_like</span></code></a>,
<em class="xref py py-obj">r</em>,
<a class="reference internal" href="../reference/generated/numpy.zeros.html#numpy.zeros" title="numpy.zeros"><code class="xref py py-obj docutils literal notranslate"><span class="pre">zeros</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.zeros_like.html#numpy.zeros_like" title="numpy.zeros_like"><code class="xref py py-obj docutils literal notranslate"><span class="pre">zeros_like</span></code></a></dd>
<dt>Conversions</dt>
<dd><a class="reference internal" href="../reference/generated/numpy.ndarray.astype.html#numpy.ndarray.astype" title="numpy.ndarray.astype"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ndarray.astype</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.atleast_1d.html#numpy.atleast_1d" title="numpy.atleast_1d"><code class="xref py py-obj docutils literal notranslate"><span class="pre">atleast_1d</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.atleast_2d.html#numpy.atleast_2d" title="numpy.atleast_2d"><code class="xref py py-obj docutils literal notranslate"><span class="pre">atleast_2d</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.atleast_3d.html#numpy.atleast_3d" title="numpy.atleast_3d"><code class="xref py py-obj docutils literal notranslate"><span class="pre">atleast_3d</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.mat.html#numpy.mat" title="numpy.mat"><code class="xref py py-obj docutils literal notranslate"><span class="pre">mat</span></code></a></dd>
<dt>Manipulations</dt>
<dd><a class="reference internal" href="../reference/generated/numpy.array_split.html#numpy.array_split" title="numpy.array_split"><code class="xref py py-obj docutils literal notranslate"><span class="pre">array_split</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.column_stack.html#numpy.column_stack" title="numpy.column_stack"><code class="xref py py-obj docutils literal notranslate"><span class="pre">column_stack</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.concatenate.html#numpy.concatenate" title="numpy.concatenate"><code class="xref py py-obj docutils literal notranslate"><span class="pre">concatenate</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.diagonal.html#numpy.diagonal" title="numpy.diagonal"><code class="xref py py-obj docutils literal notranslate"><span class="pre">diagonal</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.dsplit.html#numpy.dsplit" title="numpy.dsplit"><code class="xref py py-obj docutils literal notranslate"><span class="pre">dsplit</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.dstack.html#numpy.dstack" title="numpy.dstack"><code class="xref py py-obj docutils literal notranslate"><span class="pre">dstack</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.hsplit.html#numpy.hsplit" title="numpy.hsplit"><code class="xref py py-obj docutils literal notranslate"><span class="pre">hsplit</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.hstack.html#numpy.hstack" title="numpy.hstack"><code class="xref py py-obj docutils literal notranslate"><span class="pre">hstack</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.ndarray.item.html#numpy.ndarray.item" title="numpy.ndarray.item"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ndarray.item</span></code></a>,
<a class="reference internal" href="../reference/constants.html#numpy.newaxis" title="numpy.newaxis"><code class="xref py py-obj docutils literal notranslate"><span class="pre">newaxis</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.ravel.html#numpy.ravel" title="numpy.ravel"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ravel</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.repeat.html#numpy.repeat" title="numpy.repeat"><code class="xref py py-obj docutils literal notranslate"><span class="pre">repeat</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.reshape.html#numpy.reshape" title="numpy.reshape"><code class="xref py py-obj docutils literal notranslate"><span class="pre">reshape</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.resize.html#numpy.resize" title="numpy.resize"><code class="xref py py-obj docutils literal notranslate"><span class="pre">resize</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.squeeze.html#numpy.squeeze" title="numpy.squeeze"><code class="xref py py-obj docutils literal notranslate"><span class="pre">squeeze</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.swapaxes.html#numpy.swapaxes" title="numpy.swapaxes"><code class="xref py py-obj docutils literal notranslate"><span class="pre">swapaxes</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.take.html#numpy.take" title="numpy.take"><code class="xref py py-obj docutils literal notranslate"><span class="pre">take</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.transpose.html#numpy.transpose" title="numpy.transpose"><code class="xref py py-obj docutils literal notranslate"><span class="pre">transpose</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.vsplit.html#numpy.vsplit" title="numpy.vsplit"><code class="xref py py-obj docutils literal notranslate"><span class="pre">vsplit</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.vstack.html#numpy.vstack" title="numpy.vstack"><code class="xref py py-obj docutils literal notranslate"><span class="pre">vstack</span></code></a></dd>
<dt>Questions</dt>
<dd><a class="reference internal" href="../reference/generated/numpy.all.html#numpy.all" title="numpy.all"><code class="xref py py-obj docutils literal notranslate"><span class="pre">all</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.any.html#numpy.any" title="numpy.any"><code class="xref py py-obj docutils literal notranslate"><span class="pre">any</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.nonzero.html#numpy.nonzero" title="numpy.nonzero"><code class="xref py py-obj docutils literal notranslate"><span class="pre">nonzero</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.where.html#numpy.where" title="numpy.where"><code class="xref py py-obj docutils literal notranslate"><span class="pre">where</span></code></a></dd>
<dt>Ordering</dt>
<dd><a class="reference internal" href="../reference/generated/numpy.argmax.html#numpy.argmax" title="numpy.argmax"><code class="xref py py-obj docutils literal notranslate"><span class="pre">argmax</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.argmin.html#numpy.argmin" title="numpy.argmin"><code class="xref py py-obj docutils literal notranslate"><span class="pre">argmin</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.argsort.html#numpy.argsort" title="numpy.argsort"><code class="xref py py-obj docutils literal notranslate"><span class="pre">argsort</span></code></a>,
<a class="reference external" href="https://docs.python.org/dev/library/functions.html#max" title="(in Python v3.9)"><code class="xref py py-obj docutils literal notranslate"><span class="pre">max</span></code></a>,
<a class="reference external" href="https://docs.python.org/dev/library/functions.html#min" title="(in Python v3.9)"><code class="xref py py-obj docutils literal notranslate"><span class="pre">min</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.ptp.html#numpy.ptp" title="numpy.ptp"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ptp</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.searchsorted.html#numpy.searchsorted" title="numpy.searchsorted"><code class="xref py py-obj docutils literal notranslate"><span class="pre">searchsorted</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.sort.html#numpy.sort" title="numpy.sort"><code class="xref py py-obj docutils literal notranslate"><span class="pre">sort</span></code></a></dd>
<dt>Operations</dt>
<dd><a class="reference internal" href="../reference/generated/numpy.choose.html#numpy.choose" title="numpy.choose"><code class="xref py py-obj docutils literal notranslate"><span class="pre">choose</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.compress.html#numpy.compress" title="numpy.compress"><code class="xref py py-obj docutils literal notranslate"><span class="pre">compress</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.cumprod.html#numpy.cumprod" title="numpy.cumprod"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cumprod</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.cumsum.html#numpy.cumsum" title="numpy.cumsum"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cumsum</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.inner.html#numpy.inner" title="numpy.inner"><code class="xref py py-obj docutils literal notranslate"><span class="pre">inner</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.ndarray.fill.html#numpy.ndarray.fill" title="numpy.ndarray.fill"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ndarray.fill</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.imag.html#numpy.imag" title="numpy.imag"><code class="xref py py-obj docutils literal notranslate"><span class="pre">imag</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.prod.html#numpy.prod" title="numpy.prod"><code class="xref py py-obj docutils literal notranslate"><span class="pre">prod</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.put.html#numpy.put" title="numpy.put"><code class="xref py py-obj docutils literal notranslate"><span class="pre">put</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.putmask.html#numpy.putmask" title="numpy.putmask"><code class="xref py py-obj docutils literal notranslate"><span class="pre">putmask</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.real.html#numpy.real" title="numpy.real"><code class="xref py py-obj docutils literal notranslate"><span class="pre">real</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.sum.html#numpy.sum" title="numpy.sum"><code class="xref py py-obj docutils literal notranslate"><span class="pre">sum</span></code></a></dd>
<dt>Basic Statistics</dt>
<dd><a class="reference internal" href="../reference/generated/numpy.cov.html#numpy.cov" title="numpy.cov"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cov</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.mean.html#numpy.mean" title="numpy.mean"><code class="xref py py-obj docutils literal notranslate"><span class="pre">mean</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.std.html#numpy.std" title="numpy.std"><code class="xref py py-obj docutils literal notranslate"><span class="pre">std</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.var.html#numpy.var" title="numpy.var"><code class="xref py py-obj docutils literal notranslate"><span class="pre">var</span></code></a></dd>
<dt>Basic Linear Algebra</dt>
<dd><a class="reference internal" href="../reference/generated/numpy.cross.html#numpy.cross" title="numpy.cross"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cross</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.dot.html#numpy.dot" title="numpy.dot"><code class="xref py py-obj docutils literal notranslate"><span class="pre">dot</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.outer.html#numpy.outer" title="numpy.outer"><code class="xref py py-obj docutils literal notranslate"><span class="pre">outer</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.linalg.svd.html#numpy.linalg.svd" title="numpy.linalg.svd"><code class="xref py py-obj docutils literal notranslate"><span class="pre">linalg.svd</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.vdot.html#numpy.vdot" title="numpy.vdot"><code class="xref py py-obj docutils literal notranslate"><span class="pre">vdot</span></code></a></dd>
</dl>
</div>
</div>

## Indexing and Slicing

In [ ]:
np.random.seed(0)
arr_1 = np.random.randint(1,10,size = (4,4))
arr_1

<html>
    <table> 
        <tr><th>  </th><th>0</th><th>1</th><th>2</th><th>3</th></tr>
        <tr><td><b>0</b></td><td>6</td><td>1</td><td>4</td><td>4</td></tr>
        <tr><td><b>1</b></td><td>8</td><td>4</td><td>6</td><td>3</td></tr>
        <tr><td><b>2</b></td><td>5</td><td>8</td><td>7</td><td>9</td></tr>
        <tr><td><b>3</b></td><td>9</td><td>2</td><td>7</td><td>8</td></tr>
    </table>
</html>

### Get single element in  rows and columns

### Get multiple rows or columns

### Get subset of the matrix

## Copies and Views

In [ ]:
arr_mod = arr_1[2:,2:]
arr_mod

In [ ]:
arr_mod[:] = 2
arr_mod,arr_1

In [ ]:
arr_mod_1 = arr_1[2:,2:].copy()
arr_mod_1

In [ ]:
arr_mod_1[:] = 4
arr_mod_1,arr_1

## Boolean Indexing

In [ ]:
b1 = arr_1>2
b1

In [ ]:
arr_1[b1]

In [ ]:
brow = arr_1[0]>4
brow

In [ ]:
arr_1[:,brow]

### Where condition in numpy

In [ ]:
np.where(arr_1>2,arr_1,0)